/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalsg.componentes;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author Samil Gonzalez
 */
public class Registrar extends javax.swing.JFrame {

        MyDbconnect ConnexionBD = new MyDbconnect();
	Connection conectar= ConnexionBD.conexion();
        
    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
    }
    
    public void insertarDatos(){
			 		String MySql = "insert into usuarios (Nombre, Apellido, Telefono, Correo, UserName , Contraseña) values(?,?,?,?,?,?)";
	              
	              if((textFieldN.getText().equals("")|| textFieldApellido.getText().equals("") ||
	            	textFieldNumero.getText().equals("") || textFieldCorreo.getText().equals("") ||
	            	textFielnUsuario.getText().equals("") || textFieldPass.getText().equals("") ||
	            	textFieldPassC.getText().equals(""))) {
	            	  JOptionPane.showMessageDialog(null,"Complete todos los campos");
	            	  
	              } else {
	            	 
	                      
	                      if(textFieldPass.getText().equals(textFieldPassC.getText()))
	                      {
	                    	  try {
	                              PreparedStatement Pstatement=(PreparedStatement) conectar.prepareStatement(MySql);
	                              
	                              Pstatement.setString(1,textFieldN.getText());
	                              Pstatement.setString(2,textFieldApellido.getText());
	                              Pstatement.setString(3,textFieldNumero.getText());
	
	                              Pstatement.setString(4,textFieldCorreo.getText());
	                              Pstatement.setString(5,textFielnUsuario.getText());
	                              
	                              Pstatement.setString(6,textFieldPass.getText());
	                              
	                          Pstatement.executeUpdate();
	                          JOptionPane.showMessageDialog(null,"Usuario Registrado Exitosamente!!");
	                          
	                          } catch (SQLException e1) {
	                        	  JOptionPane.showMessageDialog(null,"No se ha podido registrar :( " + e1.getMessage());
	                          }
	                    	  
	                    	  Login AbrirLogin = new Login();
	                    	  AbrirLogin.setVisible(true);
	                    	  dispose();
	                      }
	                      else
	                      {
	                          JOptionPane.showMessageDialog(null,"Las contraseñas no coinciden");
	                      }
	                      
	              }
	
			}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        textFieldNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFielnUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textFieldCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        textFieldPass = new javax.swing.JPasswordField();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        textFieldPassC = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(240, 11, 11));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORMULARIO DE REGISTRO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 350, 40));

        jPanel5.setBackground(new java.awt.Color(240, 11, 11));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("  X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 60, 60));

        jPanel3.setBackground(new java.awt.Color(240, 11, 11));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto Black", 1, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalsg/componentes/img/flecha-hacia-atras.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        textFieldNumero.setBorder(null);
        textFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 330, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("TELEFONO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 150, 20));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 150, 20));

        textFieldN.setBorder(null);
        textFieldN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 330, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("APELLIDO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 20));

        textFieldApellido.setBorder(null);
        textFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 330, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("USUARIO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 150, -1));

        textFielnUsuario.setBorder(null);
        textFielnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFielnUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(textFielnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 330, 20));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("CORREO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 150, -1));

        textFieldCorreo.setBorder(null);
        textFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 330, 20));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("CONTRASEÑA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 150, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("CONFIRMAR CONTRASEÑA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 230, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 340, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 340, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 340, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 340, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 330, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 330, 20));

        textFieldPass.setBorder(null);
        jPanel1.add(textFieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 330, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 330, -1));

        jPanel4.setBackground(new java.awt.Color(240, 11, 11));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Roboto Black", 1, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("GUARDAR");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 190, 60));

        textFieldPassC.setBorder(null);
        jPanel1.add(textFieldPassC, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 330, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNumeroActionPerformed

    private void textFieldNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNActionPerformed

    private void textFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldApellidoActionPerformed

    private void textFielnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFielnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFielnUsuarioActionPerformed

    private void textFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCorreoActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        insertarDatos();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        Login abrirLogin = new Login();
        abrirLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       insertarDatos();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPanel4EntrarMouseExited(java.awt.event.MouseEvent evt) {                                         
        jPanel4.setBackground(new Color(248,11,11));    
    }                                        

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {                                          
       jPanel4.setBackground(new Color(252,103,103));
    }   
    /*
    private void jPanel4EntrarMouseExited(java.awt.event.MouseEvent evt) {                                         
        jPanel4.setBackground(new Color(248,11,11));    
    }                                        

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {                                          
       jPanel4.setBackground(new Color(252,103,103));
    }*/
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField textFieldApellido;
    private javax.swing.JTextField textFieldCorreo;
    private javax.swing.JTextField textFieldN;
    private javax.swing.JTextField textFieldNumero;
    private javax.swing.JPasswordField textFieldPass;
    private javax.swing.JPasswordField textFieldPassC;
    private javax.swing.JTextField textFielnUsuario;
    // End of variables declaration//GEN-END:variables
}
